### ISSUE TITLE
Fetch states by slot (nimbus support)

### ISSUE THREAD

**Issue by arnetheduck** [samcm/checkpointz#64]
Nimbus does not index historical states by root (because this index is not used anywhere in the  core protocol) - however, any historical state back to genesis is available by slot instead, which is safe because there is only one finalized history - replacing the state call to fetch states by slot will allow Nimbus as a full backend as well.

**Comment by samcm** [comment]
Great to know, I’ll have a look at implementing that. Thanks @arnetheduck!
